# Generated by Django 3.2.5 on 2022-04-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsersMood',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('mood', models.CharField(max_length=10)),
            ],
        ),
    ]
